# Generated by Django 5.0.2 on 2024-11-16 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='qtd_kgs',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
