# Generated by Django 5.0.2 on 2024-12-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_venda_descricao_venda_alter_venda_nome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'pix'), ('DINHEIRO', 'dinheiro')], default='PIX', max_length=10),
        ),
    ]
