# Generated by Django 5.0.2 on 2024-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_venda_valor_total_alter_venda_metodo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_un_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
